version: "3.9"

services:
  aggregator-api:
    build: .
    container_name: aggregator-api
    ports:
      - "8005:8000"
    restart: always
    networks:
      - parser-network

networks:
  parser-network:
    external: true
